config/routes.rb
Rails.application.routes.draw do

  resources :activation, only: [:edit]

  match 'answ_report/:test' => 'answ#show_report', :via => :get, :as => :answ_report
  match 'answ_create/' => 'answ#create_answ', :via => :post, :as => :answ_create

  post 'user_signup', to: 'users#create'

  devise_for :users, controllers: {sessions: 'users/sessions'}

  root to: 'static_pages#home'

  get 'administration', to: 'teacher_admin#index'

  get 'administration_download_user/:id' => 'teacher_admin#download_user', :via => :get, :as => :administration_download_user
  get 'administration_download_users/:id' => 'teacher_admin#download_all', :via => :get, :as => :administration_download_users

  match 'users_complete/:id/:text/:task_id' => 'users#edit_complete', :via => :get, :as => :users_complete
  match 'users_rework/:id/:text/:task_id' => 'users#edit_rework', :via => :get, :as => :users_rework

  match 'users_feedback/:id/:task_id' => 'users#edit_feedback', :via => :post, :as => :users_feedback

  match 'user_update_group/:id/:group_id' => 'users#update_group_id', :via => :put, :as => :user_update_task

  match 'check_answ/:id' => 'teacher_admin#check_answ', :via => :get, :as => :check_answ

  match 'group/:id' => 'groups#destroy', :via => :delete, :as => :group_destroy

  match 'answ_show/:id/:group_id' => 'answ#show', :via => :get, :as => :answ_show

  resources :teacher_admin_controller
  resources :answ
  resources :tasks
  resources :users
  resources :groups

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  get '/index_user', to: 'users#index'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

end

app/models/task.rb
class Task < ApplicationRecord
  has_many :answers, dependent: :destroy
  validates :content, presence: true, length: { maximum: 1000 }
  validates :content, presence: true, length: { minimum: 1, message: "only allows letters" }
  validates :name, presence: true, length: { maximum: 50 }
  validates :name, presence: true, length: { minimum: 1, message: "only allows letters"}


  def users_in_task(task_id)
    ids = "SELECT user_id FROM answers
           WHERE task_id = #{task_id}"
    User.where("id IN (#{ids})")
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :logged_in_user
  before_action :teacher, except: [:show]
  before_action :activated

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    if task.save
      tasks_group = TaskGroup.new(task_id: task.id, group_id: params[:task][:group_id])
      tasks_group.save
      flash[:success] = 'Task was created'
      redirect_to group_url(params[:task][:group_id])
    else
      redirect_to new_task_url(params[:task][:group_id])
    end
  end

  def edit
    @task = Task.find(params[:id])
    @users = User.all
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      flash[:success] = 'Task updated'
      redirect_to group_url(TaskGroup.find_by_task_id(params[:id]).group_id)
    else
      redirect_to edit_task_url(params[:id])
    end
  end

  def show
    @task = Task.find(params[:id])
    @student_answer = Answer.where(task_id: params[:id], user_id: current_user.id).last
  end

  def destroy
    group = TaskGroup.find_by_task_id(params[:id]).group_id
    Task.find(params[:id]).destroy
    redirect_to group_path(group)
  end

  private

  def task_params
    params.require(:task).permit(:name, :content)
  end
end

app/views/tasks/_task.html.erb
  <p>
    <%if current_teacher(params[:id])%>
      <%= link_to "Task: #{task.name} ", task_path(task) , class: "btn btn-lg btn-primary" %>
      <%= link_to "Edit: ", edit_task_path(task) , class: "btn btn-lg btn-primary" %>
      <% @users_all = GroupUser.where(group_id: params[:id]) %>
      <% @users_sent = Answer.where(task_id: task.id, sending: true, status: 'complete') %>
      <%=link_to "[ #{@users_sent.count} /  #{@users_all.count} ]",    answ_show_path(task, params[:id])   %>
      <%= link_to "[delete task]", task, method: :delete, data: { confirm: "You sure?" } %>
    <%else%>
        <%= link_to "Task: #{task.name} ", task_path(task.id) , class: "btn btn-lg btn-primary" %>
    <%end%>
  </p>

app/views/tasks/edit.html.erb
<% provide(:title, "Edit user") %>

  <div class="left jumbotron">
    <h1>Update the task</h1>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <% @meta = true %>
          <%= form_for(@task) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="field">
               <%= f.label :name %>
               <%= f.text_area :name, class: 'form-control' %>
               <%= f.label :content %>
               <%= f.text_area :content, class: 'form-control' %>
            </div>
            <%=f.submit "Save changes", class: "btn btn-primary" %>
          <%end%>
        </div>
      </div>
  </div>

app/views/tasks/new.html.erb
<% provide(:title, "Edit user") %>
<div class="left jumbotron">
<h1>Update the task</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@task) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_area :name, class: 'form-control' %>
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control' %>
        <%= f.hidden_field :group_id, value: params[:format] %>
      </div>
      <%= f.submit "Create task", class: "btn btn-primary" %>
    <% end %>
  </div>
  </div>
</div>

app/views/tasks/show.html.erb
<% provide(:title,"My task") %>

  <div class="center jumbotron">
    <h1> My task : </h1>
    <% unless @student_answer.nil?  %>
      <h3>{<%= @task.content%>}</h3>
      <%if @student_answer.status == "complete" %>
        <h3 style="color:#008000">[<%= @student_answer.status %>]</h3>
      <%else%>
        <h3 style="color:#ff0000">[<%= @student_answer.status %>]</h3>
      <%end%>
      <% unless @student_answer.status == "complete" || @student_answer.final == true || @student_answer.status == "In process"  %>
        <%=link_to "Send my answer", new_answ_path(params[:id]) , class: "btn btn-lg btn-primary" %>
      <% else %>
        <h3>Ur task is done..Or u already sent the task.</h3>
      <% end %>
    <% else %>
      <h3>{<%= @task.content%>}</h3>
      <%=link_to "Send my answer", new_answ_path(params[:id]) , class: "btn btn-lg btn-primary" %>
    <%end%>
  </div>