config/routes.rb
Rails.application.routes.draw do

  resources :activation, only: [:edit]

  match 'answ_report/:test' => 'answ#show_report', :via => :get, :as => :answ_report
  match 'answ_create/' => 'answ#create_answ', :via => :post, :as => :answ_create

  post 'user_signup', to: 'users#create'

  devise_for :users, controllers: {sessions: 'users/sessions'}

  root to: 'static_pages#home'

  get 'administration', to: 'teacher_admin#index'

  get 'administration_download_user/:id' => 'teacher_admin#download_user', :via => :get, :as => :administration_download_user
  get 'administration_download_users/:id' => 'teacher_admin#download_all', :via => :get, :as => :administration_download_users

  match 'users_complete/:id/:text/:task_id' => 'users#edit_complete', :via => :get, :as => :users_complete
  match 'users_rework/:id/:text/:task_id' => 'users#edit_rework', :via => :get, :as => :users_rework

  match 'users_feedback/:id/:task_id' => 'users#edit_feedback', :via => :post, :as => :users_feedback

  match 'user_update_group/:id/:group_id' => 'users#update_group_id', :via => :put, :as => :user_update_task

  match 'check_answ/:id' => 'teacher_admin#check_answ', :via => :get, :as => :check_answ

  match 'group/:id' => 'groups#destroy', :via => :delete, :as => :group_destroy

  match 'answ_show/:id/:group_id' => 'answ#show', :via => :get, :as => :answ_show

  resources :teacher_admin_controller
  resources :answ
  resources :tasks
  resources :users
  resources :groups

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  get '/index_user', to: 'users#index'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

end

app/controllers/teacher_admin_controller.rb
class TeacherAdminController < ApplicationController
  before_action :logged_in_user
  before_action :teacher
  before_action :activated


  def download_user
    SendToDropboxJob.set(wait: 5.seconds).perform_later(params[:id], params[:format])
    flash[:success] = 'Answer was sent to Dropbox'
    redirect_to administration_path
  end

  def download_all
    SendToDropboxAllJob.set(wait: 5.seconds).perform_later(params[:id])
    flash[:success] = 'Answers was sent to Dropbox'
    redirect_to administration_path
  end

  def check_answ
    @user = User.find_by_id(params[:id])
    @answer = Answer.where(task_id: params[:format], user_id: params[:id]).last
    text = RestClient.get "https://api.judge0.com/submissions/#{@answer.content}?
                            #{judge_params}"
    @text = text.split(',')
  end
end

app/helpers/teacher_admin_helper.rb
module TeacherAdminHelper
end

app/views/teacher_admin/check_answ.html.erb
<% provide(:title,"Home") %>
  <title> <%= full_title(yield(:title)) %> </title>
  <div class="left jumbotron">
    <h1> Student's answer: </h1>
    <div class="center jumbotron">
      <% if @answer.status == "complete" %>
        <h3 style="color:#008000">[<%= @answer.status %>]</h3>
      <%else%>
        <h3 style="color:#ff0000">[<%= @answer.status %>]</h3>
      <% end %>

      <% if @answer.final == true %>
        <h3 style="color:#008000">[<%= "final" %>]</h3>
      <% else %>
        <h3 style="color:#ff0000">[<%= "not final" %>]</h3>
      <% end %>
    </div>

    <%@text.each do |text|%>
      <p><%=text%></p>
      <%break if text == "compile_output"%>
    <%end%>
    <div class="center jumbotron">
      <h4>
        <%unless @answer.status == "complete" %>
          <%= form_for(:feedback, url: users_feedback_path(@user, params[:format])) do |f| %>
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control', placeholder: "Compose the feedback..." %>
            <%if @answer.final%>
              <%= f.submit "complete", name: 'complete', class: "btn btn-primary" %>
            <%end%>
            <p>  </p>
            <%= f.submit "rework", name: 'rework', class: "btn btn-primary" %>
          <%end%>
        <%else%>
          <%= link_to "Download this task", administration_download_user_url(params[:id],@answer.task_id), class: "btn btn-primary" %>
        <%end%>
      </h4>
    </div>
  </div>

app/views/teacher_admin/index.html.erb
<div class="left jumbotron">

  <h1>Administration panel</h1>

  <%if current_user.teacher && Group.find_by_teacher_id(current_user.id).nil?%>
    <%= link_to "Create new group", new_group_path , class: "btn btn-lg btn-primary" %>
  <%else%>
    <%= link_to "#{Group.find_by_teacher_id(current_user.id).name}", group_path(Group.find_by_teacher_id(current_user.id)) , class: "btn btn-lg btn-primary" %>
    <%= link_to "Edit", edit_group_url(Group.find_by_teacher_id(current_user.id)), class: "btn btn-lg btn-primary" %>
    <%= link_to "[delete group]", group_destroy_path(Group.find_by_teacher_id(current_user.id)), method: :delete, data: { confirm: "You sure?" }, class: "btn btn-lg btn-primary" %>
  <%end%>
  <p></p>
  <%= link_to "Create new student", new_user_path , class: "btn btn-lg btn-primary" %>
  <p></p>

</div>