config/routes.rb
Rails.application.routes.draw do

  resources :activation, only: [:edit]

  match 'answ_report/:test' => 'answ#show_report', :via => :get, :as => :answ_report
  match 'answ_create/' => 'answ#create_answ', :via => :post, :as => :answ_create

  post 'user_signup', to: 'users#create'

  devise_for :users, controllers: {sessions: 'users/sessions'}

  root to: 'static_pages#home'

  get 'administration', to: 'teacher_admin#index'

  get 'administration_download_user/:id' => 'teacher_admin#download_user', :via => :get, :as => :administration_download_user
  get 'administration_download_users/:id' => 'teacher_admin#download_all', :via => :get, :as => :administration_download_users

  match 'users_complete/:id/:text/:task_id' => 'users#edit_complete', :via => :get, :as => :users_complete
  match 'users_rework/:id/:text/:task_id' => 'users#edit_rework', :via => :get, :as => :users_rework

  match 'users_feedback/:id/:task_id' => 'users#edit_feedback', :via => :post, :as => :users_feedback

  match 'user_update_group/:id/:group_id' => 'users#update_group_id', :via => :put, :as => :user_update_task

  match 'check_answ/:id' => 'teacher_admin#check_answ', :via => :get, :as => :check_answ

  match 'group/:id' => 'groups#destroy', :via => :delete, :as => :group_destroy

  match 'answ_show/:id/:group_id' => 'answ#show', :via => :get, :as => :answ_show

  resources :teacher_admin_controller
  resources :answ
  resources :tasks
  resources :users
  resources :groups

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  get '/index_user', to: 'users#index'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "student app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>

        <% if user_signed_in? %>

          <li><%= link_to "Users", index_user_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", root_path %></li>
              <li><%= link_to "Settings", '#' %></li>
              <% if current_user.teacher? %>
                <li><%= link_to "Administration", administration_path %></li>
                <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path , method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title><%= full_title(yield(:title)) %></title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all',
                                 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= render 'layouts/shim' %>
    </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end%>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>